### ISSUE TITLE
поддержка python2

### ISSUE THREAD

**Issue by ibmsdave** [thepurple/pyoocalc#1]
прошу прощения за русский язык..

судя по тестам, pyoocalc неплохо работает и под python 2.7.9.
как понимаю, что поддержка python2 не входит в планы данного проекта?

**Comment by thepurple** [comment]
Не страшно, русский я так же знаю :)
В теории должно работать на 2.7, но в практике не проверял, т.к. у меня нет
готового окружения pyuno2, а собирать вручную и разворачивать нет времени.


2016-02-01 13:13 GMT+02:00 ibmsdave <notifications@github.com>:
