### ISSUE TITLE
Чтение формул из xls|xlsx

### ISSUE THREAD

**Issue by unreg** [thepurple/pyoocalc#5]
Привет!
Может я не по адресу, но поиск не очень помог,  uno умеет нормально читать посчитанные значения формул из xls? Пробовал на libbreoffice 4.4 и 5.2 в `--headless`.

Из excel-файлов читает только саму формулу:
```
$ python3.4 test.py 
PyOOCalc version: 0.0.5
Cell 'Sheet1:value1': 1.0
Cell 'Sheet1:value2': 2.0
Cell 'Sheet2:result1': =$Sheet1.A1+$Sheet1.B1
Cell 'Sheet2:result2': =SUM($Sheet1.A1;$Sheet1.B1)
```

Автоматически тип ячейки определяется как `<uno.Enum com.sun.star.table.CellContentType ('VALUE')>`, принудительно `oCell.getFormula()` тоже читает строку, а не результат.

**Comment by thepurple** [comment]
Этот вопрос не интересовал и не могу ответить. Изучать сейачс это нет времени.

Как вариант могу предложить:
- Открыть xls
- Сохранить как ods
- Открыть ods 
- Получить значения формул

Понятное дело, что не рационально, но возможно этот вариант удовлетворит.

**Comment by thepurple** [comment]
I guess this issue is not actual any more and it can be solved in the way that I have proposed.
